// search.js
const predefinedResults = {
  // Films d'Action
  "Action": "action.html",
  "Black Adam": "pages/blackadam.html",
  "Bullet Train": "pages/bullettrain.html",
  "En Eaux Troubles": "pages/meg.html",
  "En Eaux Très Troubles": "pages/megtwo.html",
  "Gran Turismo": "pages/granturismo.html",
  "Hunger Games": "pages/hungergames.html",
  "Hunger Games 2": "pages/hungergamestwo.html",
  "Hunger Games 3": "pages/hungergamesthree.html",
  "Hunger Games 4": "pages/hungergamesfour.html",
  "John Wick": "pages/johnwick.html",
  "John Wick 2": "pages/johnwicktwo.html",
  "John Wick 3": "pages/johnwickthree.html",
  "John Wick 4": "pages/johnwickfour.html",
  "Les Trois Mousquetaires": "pages/troismousquetaires.html",
  "Men In Black": "pages/mib.html",
  "Men In Black 2": "pages/mibtwo.html",
  "Men In Black 3": "pages/mibthree.html",
  "Men In Black Internationnal (4)": "pages/mibfour.html",
  "Tenet": "pages/tenet.html",
  "Tetris": "pages/tetris.html",
  "Top Gun": "pages/topgun.html",
  "Top Gun Maverick": "pages/topguntwo.html",
  // Films d'Animation
  "Animation": "animation.html",
  "Angry Birds": "animations.html#angryBirds",
  "Angry Birds 2": "animations.html#angryBirdsTwo",
  "Bienvenue chez les Louds": "animation.html#loud",
  "Bob l'Éponge le Film": "animation.html#spongebob",
  "Bob l'Éponge le Film: un Héros sort de l'Eau": "animation.html#spongebobTwo",
  "Bob l'Éponge le Film: Éponge en Eaux Troubles": "animation.html#spongebobThree",
  "Bob l'Éponge: la Quatrième Immersion": "animation.html#spongebobFour",
  "Buzz l'Éclair": "animation.html#buzzLightyear",
  "Buzz l'Éclair VOSTFR": "animation.html#buzzLightyearVOSTFR",
  "Élémentaire": "animation.html#elemental",
  "Élémentaire VOSTFR": "animation.html#elementalVOSTFR",
  "Hilda et le Roi de la Montagne": "animation.html#hilda",
  "Hôtel Transylvanie": "animation.html#hotelTransylvania",
  "Hôtel Transylvanie 2": "animation.html#hotelTransylvaniaTwo",
  "Hôtel Transylvanie 3": "animation.html#hotelTransylvaniaThree",
  "Hôtel Transylvanie Transformania": "animation.html#hotelTransylvaniaFour",
  "l'Âge de Glace": "animation.html#iceAge",
  "l'Âge de Glace 2": "animation.html#iceAgeTwo",
  "l'Âge de Glace 3: le Temps des Dinosaures": "animation.html#iceAgeThree",
  "l'Âge de Glace 4: la Dérive des Continents": "animation.html#iceAgeFour",
  "l'Âge de Glace 5: les Lois de l'Univers": "animation.html#iceAgeFive",
  "l'Âge de Glace: les Aventures de Buck Wild": "animation.html#buckWild",
  "Le Chat Potté": "animation.html#pussInBoots",
  "Le Chat Potté: les Trois Petits Diables": "animation.html#pussInBootsSpinoff",
  "Le Chat Potté 2: la Dernière Quête": "animation.html#pussInBootsTwo",
  "Le Chat Potté 2: la Dernière Quête VOSTFR": "animation.html#pussInBootsTwoVOSTFR",
  "Les Minions": "animation.html#minions",
  "Les Minions 2: Il était une fois Gru": "animation.html#minionsTwo",
  "Les Minions 2: Il était une fois Gru VOSTFR": "animation.html#minionsTwoVOSTFR",
  "La Ferme en Folie": "film/animation.html#barnyard",
  "Le Grand Méchant Renard": "animation.html#badFox",
  "Madagascar": "animation.html#madagascar",
  "Madagascar 2": "animation.html#madagascarTwo",
  "Madagascar 3": "animation.html#madagascarThree",
  "Monstres vs Aliens": "animation.html#monstrerVsAliens",
  "Moi, Moche et Méchant": "animation.html#despicableMe",
  "Moi, Moche et Méchant 2": "animation.html#despicableMeTwo",
  "Moi, Moche et Méchant 3": "animation.html#despicableMeThree",
  "Mune": "animation.html#mune",
  "Nimona": "animation.html#nimona",
  "Nimona VOSTFR": "animation.html#nimonaVOSTFR",
  "Royal Corgi": "animation.html#royalCorgi",
  "Sausage Party": "animation.html#sausageParty",
  "Sonic le Film": "animation.html#sonic",
  "Sonic 2 le Film": "animation.html#sonicTwo",
  "Sonic 2 le Film VOSTFR": "animation.html#sonicTwoVOSTFR",
  "Spider-Man: New Generation": "animation.html#spidermanIntoSpiderverse",
  "Spider-Man Across the Spider-Verse": "animation.html#spidermanAcrossSpiderverse",
  "Spider-Man Across the Spider-Verse VOSTFR": "animation.html#spidermanAcrossSpiderverseVOSTFR",
  "Super Mario Bros. le Film": "animation.html#superMarioBros",
  "Super Mario Bros. le Film VOSTFR": "animation.html#superMarioBrosVOSTFR",
  "Les Bad Guys": "animation.html#badGuys",
  "Les Bad Guys VOSTFR": "animation.html#badGuysVOSTFR",
  "Tic et Tac: les Rangers du Risque": "animation.html#chipDale",
  "Tic et Tac: les Rangers du Risque VOSTFR": "animation.html#chipDaleVOSTFR",
  "Les Tortues Ninja": "animation.html#ninjaTurtles",
  "Les Tortues Ninja VOSTFR": "animation.html#ninjaTurtlesVOSTFR",
  "Totally Spies le Film": "animation.html#totallySpies",
  // Films d'Aventure
  "Aventure": "aventure.html",
  "Avatar": "action.html#avatar",
  "Avatar 2": "action.html#avatarTwo",
  "Donjons & Dragons": "action.html#dungeonsDragons",
  "Harry Potter à l'École des Sorcier": "action.html#harryPotter",
  "Harry Potter et la Chambre des Secrets": "action.html#harryPotterTwo",
  "Harry Potter et le Prisonnier d'Azkaban": "action.html#harryPotterThree",
  "Harry Potter et la Coupe de Feu": "action.html#harryPotterFour",
  "Harry Potter et l'Ordre du Phoenix'": "action.html#harryPotterFive",
  "Harry Potter et les Reliques de la Mort Partie 1'": "action.html#harryPotterSeven",
  "Harry Potter et les Reliques de la Mort Partie 2'": "action.html#harryPotterEight",
  "Indiana Jones: les Aventuriers de l'Arche Perdue": "action.html#indianaJones",
  "Indiana Jones et le Temple Maudit": "action.html#indianaJonesTwo",
  "Indiana Jones et le Crâne de Cristal": "action.html#indianaJonesFour",
  "Indiana Jones et le Cadran de la Destinée": "action.html#indianaJonesFive",
  "La Petite Sirène": "action.html#littleMermaid",
  "Le Seigneur des Anneaux: La Communauté de l'Anneaux": "action.html#powerRing",
  "Le Seigneur des Anneaux: Les Deux Tours": "action.html#powerRingTwo",
  "Le Seigneur des Anneaux: Le Retour du Roi": "action.html#powerRingThree",
  "Les Animaux Fantastiques": "action.html#fantasticBeasts",
  "Les Animaux Fantastiques: Les Crimes de Grinderwald": "action.html#fantasticBeastsTwo",
  "Les Animaux Fantastiques: Les Secrets de Dumbledore": "action.html#fantasticBeastsThree",
  "Pirates des Caraïbes: La Malédiction du Black Pearl": "action.html#piratesCaribbean",
  "Pirates des Caraïbes: Le Secret du Coffre Maudit": "action.html#piratesCaribbeanTwo",
  "Pirates des Caraïbes: Jusqu'au Bout du Monde": "action.html#piratesCaribbeanThree",
  "Pirates des Caraïbes: La Fontaine de Jouvence": "action.html#piratesCaribbeanFour",
  "Pirates des Caraïbes: La Vengeance de Salazar": "action.html#piratesCaribbeanFive",
  //Biopic
  "Churchill": "biopic.html#churchill",
  "De Gaulle": "biopic.html#deGaulle",
  "Lamborghini: l'Homme derrière la Légende": "biopic.html#lamborghini",
  "Le Fondateur": "biopic.html#fondator",
  "Le Mans 66": "biopic.html#mans66",
  "Les Figures de l'Ombre": "biopic.html#figuresOmbre",
  "Lincoln": "biopic.html#lincoln",
  //Comédie
  "10 Jours sans Maman": "comedie.html#10Jours",
  "10 Jours Encore sans Maman": "comedie.html#10JoursTwo",
  "Les 11 Commandements": "comedie.html#11Commandements",
  "30 Jours Max": "comedie.html#30JoursMax",
  "3 Jours Max": "comedie.html#3JoursMax",
  "Ace Ventura": "comedie.html#aceVentura",
  "Ace Ventura en Afrique": "comedie.html#aceVenturaTwo",
  "Alibi.com": "comedie.html#alibiCom",
  "Alibi.com 2": "comedie.html#alibiComTwo",
  "Asteroid City": "comedie.html#asteroidCity",
  "Babylon": "comedie.html#babylon",
  "Barbie": "comedie.html#barbie",
  "BDR": "comedie.html#bde",
  "Bruce Tout Puissant": "comedie.html#brucePuissant",
  "Charlie et la Chocolaterie": "comedie.html#charlieChocolaterie",
  // Séries
  "1899": "https://flcorp.github.io/flcflix/series/1899.html",
  "American Horror Story": "https://flcorp.github.io/flcflix/series/ahs.html",
  "American Horror Story Saison 2": "https://flcorp.github.io/flcflix/series/ahs.html#Season2",
  "American Horror Story Saison 3": "https://flcorp.github.io/flcflix/series/ahs.html#Season3",
  "American Horror Story Saison 4": "https://flcorp.github.io/flcflix/series/ahs.html#Season4",
  "American Horror Story Saison 5": "https://flcorp.github.io/flcflix/series/ahs.html#Season5",
  "American Horror Story Saison 6": "https://flcorp.github.io/flcflix/series/ahs.html#Season6",
  "American Horror Story Saison 7": "https://flcorp.github.io/flcflix/series/ahs.html#Season7",
  "Amphibia": "https://flcorp.github.io/flcflix/series/amphibia.html",
  "Amphibia Saison 2": "https://flcorp.github.io/flcflix/series/amphibia.html#Season2",
  "Arcane": "https://flcorp.github.io/flcflix/series/arcane.html",
  "Better Call Saul": "https://flcorp.github.io/flcflix/series/bettercallsaul.html",
  "Better Call Saul Saison 2": "https://flcorp.github.io/flcflix/series/bettercallsaul.html#Season2",
  "Breaking Bad": "https://flcorp.github.io/flcflix/series/breakingbad.html",
  "Breaking Bad Saison 2": "https://flcorp.github.io/flcflix/series/breakingbad.html#Season2",
  "Breaking Bad Saison 3": "https://flcorp.github.io/flcflix/series/breakingbad.html#Season3",
  "Breaking Bad Saison 4": "https://flcorp.github.io/flcflix/series/breakingbad.html#Season4",
  "Breaking Bad Saison 5": "https://flcorp.github.io/flcflix/series/breakingbad.html#Season5",
  "Celebrity Hunted": "https://flcorp.github.io/flcflix/series/celebrityhunted.html",
  "Celebrity Hunted Saison 2": "https://flcorp.github.io/flcflix/series/celebrityhunted.html#Season2",
  "Dahmer: Monstre": "https://flcorp.github.io/flcflix/series/dahmer.html",
  "Dead End": "https://flcorp.github.io/flcflix/series/deadend.html",
  "Dead End Saison 2": "https://flcorp.github.io/flcflix/series/deadend.html#Season2",
  "Doctor Who": "https://flcorp.github.io/flcflix/series/drwho.html",
  "Doctor Who Saison 2": "https://flcorp.github.io/flcflix/series/drwho.html#Season2",
  "Doctor Who Saison 3": "https://flcorp.github.io/flcflix/series/drwho.html#Season3",
  "En Place": "https://flcorp.github.io/flcflix/series/enplace.html",
  "Gravity Falls": "https://flcorp.github.io/flcflix/series/gravityfalls.html",
  "Gravity Falls Saison 2": "https://flcorp.github.io/flcflix/series/gravityfalls.html#Season2",
  "Halo": "https://flcorp.github.io/flcflix/series/halo.html",
  "Helluva Boss": "https://flcorp.github.io/flcflix/series/helluvaboss.html",
  "Helluva Boss Saison 2": "https://flcorp.github.io/flcflix/series/helluvaboss.html#Season2",
  "Inside Job": "https://flcorp.github.io/flcflix/series/insidejob.html",
  "Inside Job Saison 2": "https://flcorp.github.io/flcflix/series/insidejob.html#Season2",
  "Kaleidoscope": "https://flcorp.github.io/flcflix/series/kaleidoscope.html",
  "La Casa de Papel": "https://flcorp.github.io/flcflix/series/casadepapel.html",
  "La Casa de Papel Saison 2": "https://flcorp.github.io/flcflix/series/casadepapel.html#Season2",
  "La Casa de Papel Saison 3": "https://flcorp.github.io/flcflix/series/casadepapel.html#Season3",
  "La Casa de Papel Saison 4": "https://flcorp.github.io/flcflix/series/casadepapel.html#Season4",
  "La Casa de Papel Saison 5": "https://flcorp.github.io/flcflix/series/casadepapel.html#Season5",
  "Le Flambeau": "https://flcorp.github.io/flcflix/series/flambeau.html",
  "Le Livre de Boba Fett": "https://flcorp.github.io/flcflix/series/bobafett.html",
  "Les Désastreuses Aventures des Orphelins Baudelaires": "https://flcorp.github.io/flcflix/series/baudelaires.html",
  "Les Désastreuses Aventures des Orphelins Baudelaires Saison 2": "https://flcorp.github.io/flcflix/series/baudelaires.html#Season2",
  "Les Simpson": "https://flcorp.github.io/flcflix/series/simpsons.html",
  "Les Simpson Saison 2": "https://flcorp.github.io/flcflix/series/simpsons.html#Season2",
  "Les Simpson Saison 3": "https://flcorp.github.io/flcflix/series/simpsons.html#Season3",
  "Loki": "https://flcorp.github.io/flcflix/series/loki.html",
  "Loki": "https://flcorp.github.io/flcflix/series/loki.html#Season2",
  "LOL: Qui Rit, Sort!": "https://flcorp.github.io/flcflix/series/simpsons.html",
  "LOL: Qui Rit, Sort! Saison 2": "https://flcorp.github.io/flcflix/series/lol.html#Season2",
  "LOL: Qui Rit, Sort! 3": "https://flcorp.github.io/flcflix/series/lol.html#Season3",
  "Malcolm": "https://flcorp.github.io/flcflix/series/malcolm.html",
  "Malcolm Saison 2": "https://flcorp.github.io/flcflix/series/malcolm.html#Season2",
  "Murder Drones": "https://flcorp.github.io/flcflix/series/murderdrones.html",
  "One Piece": "https://flcorp.github.io/flcflix/series/onepiece.html",
  "Peaky Blinders": "https://flcorp.github.io/flcflix/series/peakyblinders.html",
  "Peaky Blinders Saison 2": "https://flcorp.github.io/flcflix/series/peakyblinders.html#Season2",
  "Peaky Blinders Saison 3": "https://flcorp.github.io/flcflix/series/peakyblinders.html#Season3",
  "Rick et Morty": "https://flcorp.github.io/flcflix/series/rick&morty.html",
  "Rick et Morty Saison 2": "https://flcorp.github.io/flcflix/series/rick&morty.html#Season2",
  "Rick et Morty Saison 3": "https://flcorp.github.io/flcflix/series/rick&morty.html#Season3",
  "Rick et Morty Saison 4": "https://flcorp.github.io/flcflix/series/rick&morty.html#Season4",
  "Rick et Morty Saison 5": "https://flcorp.github.io/flcflix/series/rick&morty.html#Season5",
  "Rick et Morty Saison 6": "https://flcorp.github.io/flcflix/series/rick&morty.html#Season6",
  "Secret Invasion": "https://flcorp.github.io/flcflix/series/secretinvasion.html",
  "Seul Face à l'Abeille": "https://flcorp.github.io/flcflix/series/manvsbee.html",
  "Sherlock": "https://flcorp.github.io/flcflix/series/sherlock.html",
  "Sherlock Saison 2": "https://flcorp.github.io/flcflix/series/sherlock.html#Season2",
  "Sherlock Saison 3": "https://flcorp.github.io/flcflix/series/sherlock.html#Season3",
  "Sonic Prime": "https://flcorp.github.io/flcflix/series/sonic.html",
  "Sonic Prime Saison 2": "https://flcorp.github.io/flcflix/series/sonic.html#Season2",
  "Squid Game": "https://flcorp.github.io/flcflix/series/squidgame.html",
  "Stranger Things": "https://flcorp.github.io/flcflix/series/strangerthings.html",
  "Stranger Things Saison 2": "https://flcorp.github.io/flcflix/series/strangerthings.html#Season2",
  "Stranger Things Saison 3": "https://flcorp.github.io/flcflix/series/strangerthings.html#Season3",
  "Stranger Things Saison 4": "https://flcorp.github.io/flcflix/series/strangerthings.html#Season4",
  "The Boys": "https://flcorp.github.io/flcflix/series/theboys.html",
  "The Boys Saison 2": "https://flcorp.github.io/flcflix/series/theboys.html#Season2",
  "The Boys Saison 3": "https://flcorp.github.io/flcflix/series/theboys.html#Season3",
  "The Flash": "https://flcorp.github.io/flcflix/series/flash.html",
  "The Last of Us": "https://flcorp.github.io/flcflix/series/lastofus.html",
  "The Mandalorian": "https://flcorp.github.io/flcflix/series/mandaloian.html",
  "The Mandalorian Saison 2": "https://flcorp.github.io/flcflix/series/mandaloian.html#Season2",
  "The Mandalorian Saison 3": "https://flcorp.github.io/flcflix/series/mandaloian.html#Season3",
  "The Punisher": "https://flcorp.github.io/flcflix/series/punisher.html",
  "The Walking Dead": "https://flcorp.github.io/flcflix/series/walkingdead.html",
  "The Walking Dead Saison 2": "https://flcorp.github.io/flcflix/series/walkingdead.html#Season2",
  "The Walking Dead Saison 3": "https://flcorp.github.io/flcflix/series/walkingdead.html#Season3",
  "The Owl House": "https://flcorp.github.io/flcflix/series/toh.html",
  "Tulsa King": "https://flcorp.github.io/flcflix/series/tulsaking.html",
  "Umbrella Academy": "https://flcorp.github.io/flcflix/series/umbrellaacademy.html",
  "Umbrella Academy Saison 2": "https://flcorp.github.io/flcflix/series/umbrellaacademy.html#Season2",
  "Umbrella Academy Saison 3": "https://flcorp.github.io/flcflix/series/umbrellaacademy.html#Season3",
  "You": "https://flcorp.github.io/flcflix/series/you.html",
  "You Saison 2": "https://flcorp.github.io/flcflix/series/you.html#Season2",
  "You Saison 3": "https://flcorp.github.io/flcflix/series/you.html#Season3",
  "Young Rock": "https://flcorp.github.io/flcflix/series/youngrock.html",
  "Young Rock Saison 2": "https://flcorp.github.io/flcflix/series/youngrock.html#Season2",
  "Zootopie+": "https://flcorp.github.io/flcflix/series/zootopia.html",
};

  const searchInput = document.getElementById("search-input");
  const resultList = document.getElementById("result-list");
  
  // Fonction de recherche
  function search() {
    const searchTerm = searchInput.value;
    resultList.innerHTML = ""; // Efface les résultats actuels
  
    if (searchTerm.trim() === "") {
      return; // Ne rien afficher si la recherche est vide
    }
  
    for (const key in predefinedResults) {
      if (key.includes(searchTerm)) {
        const li = document.createElement("li");
        const link = document.createElement("a");
        link.textContent = key;
        link.href = predefinedResults[key];
        li.appendChild(link);
        resultList.appendChild(li);
      }
    }
  }
  
  // Écouteur d'événement pour la recherche à chaque modification de l'entrée
  searchInput.addEventListener("input", search);