// search.js
const predefinedResults = {
  // Films d'Action
  "Action": "https://flcorp.github.io/flcflix/films/action.html",
  "Black Adam": "https://flcorp.github.io/flcflix/films/pages/blackadam.html",
  "Bullet Train": "https://flcorp.github.io/flcflix/films/pages/bullettrain.html",
  "En Eaux Troubles": "https://flcorp.github.io/flcflix/films/pages/meg.html",
  "En Eaux Très Troubles": "https://flcorp.github.io/flcflix/films/pages/megtwo.html",
  "Gran Turismo": "https://flcorp.github.io/flcflix/films/pages/granturismo.html",
  "Hunger Games": "https://flcorp.github.io/flcflix/films/pages/hungergames.html",
  "Hunger Games 2": "https://flcorp.github.io/flcflix/films/pages/hungergamestwo.html",
  "Hunger Games 3": "https://flcorp.github.io/flcflix/films/pages/hungergamesthree.html",
  "Hunger Games 4": "https://flcorp.github.io/flcflix/films/pages/hungergamesfour.html",
  "Hunger Games 5": "https://flcorp.github.io/flcflix/films/pages/hungergamesfive.html",
  "John Wick": "https://flcorp.github.io/flcflix/films/pages/johnwick.html",
  "John Wick 2": "https://flcorp.github.io/flcflix/films/pages/johnwicktwo.html",
  "John Wick 3": "https://flcorp.github.io/flcflix/films/pages/johnwickthree.html",
  "John Wick 4": "https://flcorp.github.io/flcflix/films/pages/johnwickfour.html",
  "Les Trois Mousquetaires": "https://flcorp.github.io/flcflix/films/pages/troismousquetaires.html",
  "Men In Black": "https://flcorp.github.io/flcflix/films/pages/mib.html",
  "Men In Black 2": "https://flcorp.github.io/flcflix/films/pages/mibtwo.html",
  "Men In Black 3": "https://flcorp.github.io/flcflix/films/pages/mibthree.html",
  "Men In Black Internationnal (4)": "https://flcorp.github.io/flcflix/films/pages/mibfour.html",
  "Tenet": "https://flcorp.github.io/flcflix/films/pages/tenet.html",
  "Tetris": "https://flcorp.github.io/flcflix/films/pages/tetris.html",
  "Top Gun": "https://flcorp.github.io/flcflix/films/pages/topgun.html",
  "Top Gun Maverick": "https://flcorp.github.io/flcflix/films/pages/topguntwo.html",
  // Films d'Animation
  "Animation": "https://flcorp.github.io/flcflix/films/animation.html",
  "Angry Birds": "https://flcorp.github.io/flcflix/films/animations.html#angryBirds",
  "Angry Birds 2": "https://flcorp.github.io/flcflix/films/animations.html#angryBirdsTwo",
  "Bienvenue chez les Louds": "https://flcorp.github.io/flcflix/films/animation.html#loud",
  "Bob l'Éponge le Film": "https://flcorp.github.io/flcflix/films/animation.html#spongebob",
  "Bob l'Éponge le Film: un Héros sort de l'Eau": "https://flcorp.github.io/flcflix/films/animation.html#spongebobTwo",
  "Bob l'Éponge le Film: Éponge en Eaux Troubles": "https://flcorp.github.io/flcflix/films/animation.html#spongebobThree",
  "Bob l'Éponge: la Quatrième Immersion": "https://flcorp.github.io/flcflix/films/animation.html#spongebobFour",
  "Buzz l'Éclair": "https://flcorp.github.io/flcflix/films/animation.html#buzzLightyear",
  "Buzz l'Éclair VOSTFR": "https://flcorp.github.io/flcflix/films/animation.html#buzzLightyearVOSTFR",
  "Élémentaire": "https://flcorp.github.io/flcflix/films/animation.html#elemental",
  "Élémentaire VOSTFR": "https://flcorp.github.io/flcflix/films/animation.html#elementalVOSTFR",
  "Hilda et le Roi de la Montagne": "https://flcorp.github.io/flcflix/films/animation.html#hilda",
  "Hôtel Transylvanie": "https://flcorp.github.io/flcflix/films/animation.html#hotelTransylvania",
  "Hôtel Transylvanie 2": "https://flcorp.github.io/flcflix/films/animation.html#hotelTransylvaniaTwo",
  "Hôtel Transylvanie 3": "https://flcorp.github.io/flcflix/films/animation.html#hotelTransylvaniaThree",
  "Hôtel Transylvanie Transformania": "https://flcorp.github.io/flcflix/films/animation.html#hotelTransylvaniaFour",
  "l'Âge de Glace": "https://flcorp.github.io/flcflix/films/animation.html#iceAge",
  "l'Âge de Glace 2": "https://flcorp.github.io/flcflix/films/animation.html#iceAgeTwo",
  "l'Âge de Glace 3: le Temps des Dinosaures": "https://flcorp.github.io/flcflix/films/animation.html#iceAgeThree",
  "l'Âge de Glace 4: la Dérive des Continents": "https://flcorp.github.io/flcflix/films/animation.html#iceAgeFour",
  "l'Âge de Glace 5: les Lois de l'Univers": "https://flcorp.github.io/flcflix/films/animation.html#iceAgeFive",
  "l'Âge de Glace: les Aventures de Buck Wild": "https://flcorp.github.io/flcflix/films/animation.html#buckWild",
  "Le Chat Potté": "https://flcorp.github.io/flcflix/films/animation.html#pussInBoots",
  "Le Chat Potté: les Trois Petits Diables": "https://flcorp.github.io/flcflix/films/animation.html#pussInBootsSpinoff",
  "Le Chat Potté 2: la Dernière Quête": "https://flcorp.github.io/flcflix/films/animation.html#pussInBootsTwo",
  "Le Chat Potté 2: la Dernière Quête VOSTFR": "https://flcorp.github.io/flcflix/films/animation.html#pussInBootsTwoVOSTFR",
  "Les Minions": "https://flcorp.github.io/flcflix/films/animation.html#minions",
  "Les Minions 2: Il était une fois Gru": "https://flcorp.github.io/flcflix/films/animation.html#minionsTwo",
  "Les Minions 2: Il était une fois Gru VOSTFR": "https://flcorp.github.io/flcflix/films/animation.html#minionsTwoVOSTFR",
  "La Ferme en Folie": "https://flcorp.github.io/flcflix/films/animation.html#barnyard",
  "Le Grand Méchant Renard": "https://flcorp.github.io/flcflix/films/animation.html#badFox",
  "Madagascar": "https://flcorp.github.io/flcflix/films/animation.html#madagascar",
  "Madagascar 2": "https://flcorp.github.io/flcflix/films/animation.html#madagascarTwo",
  "Madagascar 3": "https://flcorp.github.io/flcflix/films/animation.html#madagascarThree",
  "Monstres vs Aliens": "https://flcorp.github.io/flcflix/films/animation.html#monstrerVsAliens",
  "Moi, Moche et Méchant": "https://flcorp.github.io/flcflix/films/animation.html#despicableMe",
  "Moi, Moche et Méchant 2": "https://flcorp.github.io/flcflix/films/animation.html#despicableMeTwo",
  "Moi, Moche et Méchant 3": "https://flcorp.github.io/flcflix/films/animation.html#despicableMeThree",
  "Mune": "https://flcorp.github.io/flcflix/films/animation.html#mune",
  "Nimona": "https://flcorp.github.io/flcflix/films/animation.html#nimona",
  "Nimona VOSTFR": "https://flcorp.github.io/flcflix/films/animation.html#nimonaVOSTFR",
  "Royal Corgi": "https://flcorp.github.io/flcflix/films/animation.html#royalCorgi",
  "Sausage Party": "https://flcorp.github.io/flcflix/films/animation.html#sausageParty",
  "Sonic le Film": "https://flcorp.github.io/flcflix/films/animation.html#sonic",
  "Sonic 2 le Film": "https://flcorp.github.io/flcflix/films/animation.html#sonicTwo",
  "Sonic 2 le Film VOSTFR": "https://flcorp.github.io/flcflix/films/animation.html#sonicTwoVOSTFR",
  "Spider-Man: New Generation": "https://flcorp.github.io/flcflix/films/animation.html#spidermanIntoSpiderverse",
  "Spider-Man Across the Spider-Verse": "https://flcorp.github.io/flcflix/films/animation.html#spidermanAcrossSpiderverse",
  "Spider-Man Across the Spider-Verse VOSTFR": "https://flcorp.github.io/flcflix/films/animation.html#spidermanAcrossSpiderverseVOSTFR",
  "Super Mario Bros. le Film": "https://flcorp.github.io/flcflix/films/animation.html#superMarioBros",
  "Super Mario Bros. le Film VOSTFR": "https://flcorp.github.io/flcflix/films/animation.html#superMarioBrosVOSTFR",
  "Les Bad Guys": "https://flcorp.github.io/flcflix/films/animation.html#badGuys",
  "Les Bad Guys VOSTFR": "https://flcorp.github.io/flcflix/films/animation.html#badGuysVOSTFR",
  "Tic et Tac: les Rangers du Risque": "https://flcorp.github.io/flcflix/films/animation.html#chipDale",
  "Tic et Tac: les Rangers du Risque VOSTFR": "https://flcorp.github.io/flcflix/films/animation.html#chipDaleVOSTFR",
  "Les Tortues Ninja": "https://flcorp.github.io/flcflix/films/animation.html#ninjaTurtles",
  "Les Tortues Ninja VOSTFR": "https://flcorp.github.io/flcflix/films/animation.html#ninjaTurtlesVOSTFR",
  "Totally Spies le Film": "https://flcorp.github.io/flcflix/films/animation.html#totallySpies",
  // Films d'Aventure
  "Aventure": "https://flcorp.github.io/flcflix/films/aventure.html",
  "Aventure VOSTFR": "https://flcorp.github.io/flcflix/films/aventure.html#vostfr",
  "Avatar": "https://flcorp.github.io/flcflix/films/action.html#avatar",
  "Avatar 2": "https://flcorp.github.io/flcflix/films/action.html#avatarTwo",
  "Donjons & Dragons": "https://flcorp.github.io/flcflix/films/action.html#dungeonsDragons",
  "Harry Potter à l'École des Sorcier": "https://flcorp.github.io/flcflix/films/action.html#harryPotter",
  "Harry Potter et la Chambre des Secrets": "https://flcorp.github.io/flcflix/films/action.html#harryPotterTwo",
  "Harry Potter et le Prisonnier d'Azkaban": "https://flcorp.github.io/flcflix/films/action.html#harryPotterThree",
  "Harry Potter et la Coupe de Feu": "https://flcorp.github.io/flcflix/films/action.html#harryPotterFour",
  "Harry Potter et l'Ordre du Phoenix'": "https://flcorp.github.io/flcflix/films/action.html#harryPotterFive",
  "Harry Potter et les Reliques de la Mort Partie 1'": "https://flcorp.github.io/flcflix/films/action.html#harryPotterSeven",
  "Harry Potter et les Reliques de la Mort Partie 2'": "https://flcorp.github.io/flcflix/films/action.html#harryPotterEight",
  "Indiana Jones: les Aventuriers de l'Arche Perdue": "https://flcorp.github.io/flcflix/films/action.html#indianaJones",
  "Indiana Jones et le Temple Maudit": "https://flcorp.github.io/flcflix/films/action.html#indianaJonesTwo",
  "Indiana Jones et le Crâne de Cristal": "https://flcorp.github.io/flcflix/films/action.html#indianaJonesFour",
  "Indiana Jones et le Cadran de la Destinée": "https://flcorp.github.io/flcflix/films/action.html#indianaJonesFive",
  "La Petite Sirène": "https://flcorp.github.io/flcflix/films/action.html#littleMermaid",
  "Le Seigneur des Anneaux: La Communauté de l'Anneaux": "https://flcorp.github.io/flcflix/films/action.html#powerRing",
  "Le Seigneur des Anneaux: Les Deux Tours": "https://flcorp.github.io/flcflix/films/action.html#powerRingTwo",
  "Le Seigneur des Anneaux: Le Retour du Roi": "https://flcorp.github.io/flcflix/films/action.html#powerRingThree",
  "Les Animaux Fantastiques": "https://flcorp.github.io/flcflix/films/action.html#fantasticBeasts",
  "Les Animaux Fantastiques: Les Crimes de Grinderwald": "https://flcorp.github.io/flcflix/films/action.html#fantasticBeastsTwo",
  "Les Animaux Fantastiques: Les Secrets de Dumbledore": "https://flcorp.github.io/flcflix/films/action.html#fantasticBeastsThree",
  "Pirates des Caraïbes: La Malédiction du Black Pearl": "https://flcorp.github.io/flcflix/films/action.html#piratesCaribbean",
  "Pirates des Caraïbes: Le Secret du Coffre Maudit": "https://flcorp.github.io/flcflix/films/action.html#piratesCaribbeanTwo",
  "Pirates des Caraïbes: Jusqu'au Bout du Monde": "https://flcorp.github.io/flcflix/films/action.html#piratesCaribbeanThree",
  "Pirates des Caraïbes: La Fontaine de Jouvence": "https://flcorp.github.io/flcflix/films/action.html#piratesCaribbeanFour",
  "Pirates des Caraïbes: La Vengeance de Salazar": "https://flcorp.github.io/flcflix/https://flcorp.github.io/flcflix/films/action.html#piratesCaribbeanFive",
  //Biopic
  "Churchill": "https://flcorp.github.io/flcflix/films/biopic.html#churchill",
  "De Gaulle": "https://flcorp.github.io/flcflix/films/biopic.html#deGaulle",
  "Lamborghini: l'Homme derrière la Légende": "https://flcorp.github.io/flcflix/films/biopic.html#lamborghini",
  "Le Fondateur": "https://flcorp.github.io/flcflix/films/biopic.html#fondator",
  "Le Mans 66": "https://flcorp.github.io/flcflix/films/biopic.html#mans66",
  "Les Figures de l'Ombre": "https://flcorp.github.io/flcflix/films/biopic.html#figuresOmbre",
  "Lincoln": "https://flcorp.github.io/flcflix/films/biopic.html#lincoln",
  //Comédie
  "10 Jours sans Maman": "https://flcorp.github.io/flcflix/films/comedie.html#10Jours",
  "10 Jours Encore sans Maman": "https://flcorp.github.io/flcflix/films/comedie.html#10JoursTwo",
  "Les 11 Commandements": "https://flcorp.github.io/flcflix/films/comedie.html#11Commandements",
  "30 Jours Max": "https://flcorp.github.io/flcflix/films/comedie.html#30JoursMax",
  "3 Jours Max": "https://flcorp.github.io/flcflix/films/comedie.html#3JoursMax",
  "Ace Ventura": "https://flcorp.github.io/flcflix/films/comedie.html#aceVentura",
  "Ace Ventura en Afrique": "https://flcorp.github.io/flcflix/films/comedie.html#aceVenturaTwo",
  "Alibi.com": "https://flcorp.github.io/flcflix/films/comedie.html#alibiCom",
  "Alibi.com 2": "https://flcorp.github.io/flcflix/films/comedie.html#alibiComTwo",
  "Asteroid City": "https://flcorp.github.io/flcflix/films/comedie.html#asteroidCity",
  "Babylon": "https://flcorp.github.io/flcflix/films/comedie.html#babylon",
  "Barbie": "https://flcorp.github.io/flcflix/films/comedie.html#barbie",
  "BDR": "https://flcorp.github.io/flcflix/films/comedie.html#bde",
  "Bruce Tout Puissant": "https://flcorp.github.io/flcflix/films/comedie.html#brucePuissant",
  "Charlie et la Chocolaterie": "https://flcorp.github.io/flcflix/films/comedie.html#charlieChocolaterie",
  // Séries
  "1899": "1899.html",
  "American Horror Story": "ahs.html",
  "Amphibia": "amphibia.html",
  "Arcane": "arcane.html",
  "Better Call Saul": "bettercallsaul.html",
  "Breaking Bad": "breakingbad.html",
  "Celebrity Hunted": "celebrityhunted.html",
  "Dahmer: Monstre": "dahmer.html",
  "Dead End": "deadend.html",
  "Doctor Who": "drwho.html",
  "En Place": "enplace.html",
  "Gravity Falls": "gravityfalls.html",
  "Halo": "halo.html",
  "Helluva Boss": "helluvaboss.html",
  "Inside Job": "insidejob.html",
  "Kaleidoscope": "kaleidoscope.html",
  "La Casa de Papel": "casadepapel.html",
  "Le Flambeau": "flambeau.html",
  "Le Livre de Boba Fett": "bobafett.html",
  "Les Simpson": "simpsons.html",
  "Loki": "loki.html",
  "LOL: Qui Rit, Sort!": "lol.html",
  "Malcolm": "malcolm.html",
  "Murder Drones": "murderdrones.html",
  "One Piece": "onepiece.html",
  "Peaky Blinders": "peakyblinders.html",
  "Rick et Morty": "rick&morty.html",
  "Secret Invasion": "secretinvasion.html",
  "Seul Face à l'Abeille": "manvsbee.html",
  "Sherlock": "sherlock.html",
  "Sonic Prime": "sonic.html",
  "Squid Game": "squidgame.html",
  "Stranger Things": "strangerthings.html",
  "The Boys": "theboys.html",
  "The Flash": "flash.html",
  "The Last of Us": "lastofus.html",
  "The Mandalorian": "mandaloian.html",
  "The Punisher": "punisher.html",
  "The Walking Dead": "walkingdead.html",
  "The Owl House": "toh.html",
  "Tulsa King": "tulsaking.html",
  "Umbrella Academy": "umbrellaacademy.html",
  "You": "you.html",
  "Young Rock": "youngrock.html",
  "Zootopie+": "zootopia.html",
};

  const searchInput = document.getElementById("search-input");
  const resultList = document.getElementById("result-list");
  
  // Fonction de recherche
  function search() {
    const searchTerm = searchInput.value;
    resultList.innerHTML = ""; // Efface les résultats actuels
  
    if (searchTerm.trim() === "") {
      return; // Ne rien afficher si la recherche est vide
    }
  
    for (const key in predefinedResults) {
      if (key.includes(searchTerm)) {
        const li = document.createElement("li");
        const link = document.createElement("a");
        link.textContent = key;
        link.href = predefinedResults[key];
        li.appendChild(link);
        resultList.appendChild(li);
      }
    }
  }
  
  // Écouteur d'événement pour la recherche à chaque modification de l'entrée
  searchInput.addEventListener("input", search);